name: Upload an APK to drive link

on: workflow_dispatch

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: create local properties
        run: touch local.properties
            
      - name: Build Debug apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload a file to Google Drive
        id: ttt3
        uses: willo32/google-drive-upload-action@v1
        with:
          target: ${{ steps.releaseApk.outputs.apkfile }}
          credentials: ${{ secrets.GOOGLE_TOKEN }}
          filename: "Release_test.apk"
          parent_folder_id: 1YqixTzEtUJKCUpHaG_5I0Gl8tE4Vx7rx
          name: "Release_test.apk"

      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      #     channel-id: learning
      #     # For posting a simple plain text message
      #     slack-message: "A new version has been uploaded to the drive https://drive.google.com/drive/folders/1YqixTzEtUJKCUpHaG_5I0Gl8tE4Vx7rx?usp=drive_link with name Release_${{ steps.t1.outputs.year }}_${{ steps.t1.outputs.month }}_${{ steps.t1.outputs.day }}_${{ steps.t1.outputs.hours }}:${{ steps.t1.outputs.minutes }}:${{ steps.t1.outputs.seconds }}.apk"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

#      - name: Upload APK to slack step
#        uses: adrey/slack-file-upload-action@master
#        with:
#            token: ${{ secrets.SLACK_TOKEN }}
#            path: app/build/outputs/apk/debug/app-debug.apk
#            channel: learning
