name: Upload an APK to drive link

on: workflow_dispatch

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: create local properties
        run: touch local.properties
            
      - name: Build Debug apk
        run: ./gradlew assembleDebug --stacktrace

      # - name: Get debug file apk path
      #   id: debugApk
      #   run: echo "apkfile=$(find app/build/outputs/apk/debug/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload a file to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: app/build/outputs/apk/debug/app-debug.apk
          credentials: ${{ secrets.GOOGLE_TOKEN }}
          parent_folder_id: 1YqixTzEtUJKCUpHaG_5I0Gl8tE4Vx7rx
         
