name: Upload an APK to drive link

on: workflow_dispatch

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # - name: create local properties
      #   run: touch local.properties
            
      # - name: Build Debug apk
      #   run: ./gradlew assembleDebug --stacktrace

      - name: create local properties
        run: touch local.properties

      # - name: Decode Keystore
      #   env:
      #     ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
      #     RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #     RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
      #     RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      #   run: |
      #       echo $ENCODED_STRING > keystore-b64.txt
      #       base64 -d keystore-b64.txt > keystore.jks
            
      # - name: Build Release apk
      #   env:
      #     RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #     RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
      #     RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      #   run: ./gradlew assembleRelease --stacktrace
        
      # - name: Get release file apk path
      #   id: releaseApk
      #   run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT
      - name: Sign app APK and release
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE_64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        
      - name: Upload a file to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: ${{ steps.sign_app.outputs.signedReleaseFile }}
          credentials: ${{ secrets.GOOGLE_TOKEN }}
          parent_folder_id: 1YqixTzEtUJKCUpHaG_5I0Gl8tE4Vx7rx
         
